### ISSUE TITLE
Please help with the setup

### ISSUE THREAD

**Issue by MIPOHBOPOHIH** [rushkii/kiizuha-genshin#1]
I made a fork of the project and inserted data( {"ltuid": myltuid, "ltoken": "mytoken"} ) into the environments/actions and thought it would update the README.md, but it does nothing
![image](https://user-images.githubusercontent.com/98014624/232828054-52b4013e-4e7a-4939-b3f2-044de7b81e98.png)
![image](https://user-images.githubusercontent.com/98014624/232828109-d746e612-ced0-486c-8f91-93e1c6e54e61.png)

**Comment by rushkii** [comment]
@MIPOHBOPOHIH can you screenshot the GitHub actions logs?

**Comment by MIPOHBOPOHIH** [comment]
![image](https://user-images.githubusercontent.com/98014624/232832803-77e62bc1-40df-4318-b00a-ee27faba389c.png)
it turns out I didn't turn on Actions... maybe it will work later

**Comment by rushkii** [comment]
> ![image](https://user-images.githubusercontent.com/98014624/232832803-77e62bc1-40df-4318-b00a-ee27faba389c.png) it turns out I didn't turn on Actions... maybe it will work later

![image](https://user-images.githubusercontent.com/47179236/232835796-d7a190ab-6287-42c0-ab26-e7864d229ffd.png)
It seems forks will not working to create a workflow actions, try `git clone` instead of fork.

**Comment by MIPOHBOPOHIH** [comment]
> > ![image](https://user-images.githubusercontent.com/98014624/232832803-77e62bc1-40df-4318-b00a-ee27faba389c.png) it turns out I didn't turn on Actions... maybe it will work later
> 
> ![image](https://user-images.githubusercontent.com/47179236/232835796-d7a190ab-6287-42c0-ab26-e7864d229ffd.png) It seems forks will not working to create a workflow actions, try `git clone` instead of fork.

![image](https://user-images.githubusercontent.com/98014624/232844722-ffbb93f5-8c66-4413-9d49-7c0809fbb958.png)
I copied the repository and filled it in, and when I tried to run the workflow,, and the error came up

**Comment by MIPOHBOPOHIH** [comment]
It turns out that I had to change something in the Actions settings, and it works now...  thanks for the help!
