### ISSUE TITLE
how to change language?

### ISSUE THREAD

**Issue by MIPOHBOPOHIH** [rushkii/kiizuha-genshin#2]
One more question, but how can I change the language in the statistics? I wish it used a different language instead of English, but when I changed ```choices=genshin. LANGS, default="en-us"``` to ```choices=genshin. LANGS, default="ru-ru"``` (this language is supported genshin.py), it just stopped working for me
![image](https://user-images.githubusercontent.com/98014624/233142261-6323cb31-faff-4c9a-80a7-5532026aabed.png)
![image](https://user-images.githubusercontent.com/98014624/233143747-e88cbd5b-1ea0-4fce-b21b-0a06ad05d39f.png)

**Comment by rushkii** [comment]
> One more question, but how can I change the language in the statistics? I wish it used a different language instead of English, but when I changed `choices=genshin. LANGS, default="en-us"` to `choices=genshin. LANGS, default="ru-ru"` (this language is supported genshin.py), it just stopped working for me ![image](https://user-images.githubusercontent.com/98014624/233142261-6323cb31-faff-4c9a-80a7-5532026aabed.png) ![image](https://user-images.githubusercontent.com/98014624/233143747-e88cbd5b-1ea0-4fce-b21b-0a06ad05d39f.png)

Hai, sorry for waiting my answer, can you change all `lang=` parameters to `ru-ru` instead?
https://github.com/rushkii/kiizuha-genshin/blob/45f740b7b049d4412ba358c2b963fc126e16f9ba/main.py#L44-L53

**Comment by MIPOHBOPOHIH** [comment]
https://github.com/MIPOHBOPOHIH/mbgenshin/actions/runs/5125311117/jobs/9218321828 

nope(

**Comment by rushkii** [comment]
> https://github.com/MIPOHBOPOHIH/mbgenshin/actions/runs/5125311117/jobs/9218321828
> 
> nope(

Try this:
https://github.com/thesadru/genshin.py/issues/109

**Comment by MIPOHBOPOHIH** [comment]
> > https://github.com/MIPOHBOPOHIH/mbgenshin/actions/runs/5125311117/jobs/9218321828
> > nope(
> 
> Try this: [thesadru/genshin.py#109](https://github.com/thesadru/genshin.py/issues/109)

https://github.com/MIPOHBOPOHIH/mbgenshin/actions/runs/5125630145/jobs/9219056774

**Comment by rushkii** [comment]
> > > https://github.com/MIPOHBOPOHIH/mbgenshin/actions/runs/5125311117/jobs/9218321828
> > > nope(
> > 
> > 
> > Try this: [thesadru/genshin.py#109](https://github.com/thesadru/genshin.py/issues/109)
> 
> https://github.com/MIPOHBOPOHIH/mbgenshin/actions/runs/5125630145/jobs/9219056774

Ugh, I don't know man, can you make a new issue on his repo? I've tested Russian language on my locale machine and it just works fine.

**Comment by MIPOHBOPOHIH** [comment]
> > > > https://github.com/MIPOHBOPOHIH/mbgenshin/actions/runs/5125311117/jobs/9218321828
> > > > nope(
> > > 
> > > 
> > > Try this: [thesadru/genshin.py#109](https://github.com/thesadru/genshin.py/issues/109)
> > 
> > 
> > https://github.com/MIPOHBOPOHIH/mbgenshin/actions/runs/5125630145/jobs/9219056774
> 
> Ugh, I don't know man, can you make a new issue on his repo? I've tested Russian language on my locale machine and it just works fine.

oh well, thanks for the help!

**Comment by MIPOHBOPOHIH** [comment]
Wow, everything was fixed when I changed default="en-us" to default="ru-ru"!
https://github.com/MIPOHBOPOHIH/mbgenshin/commit/27e78469aadfd181af6f39ca85f54738d9c59a67
